services:
  - type: web
    name: ci360backend
    runtime: node
    plan: free
    buildCommand: npm install --prefix web --include=dev && cd web && npx vite build
    startCommand: node backend/server.js
    envVars:
      - key: NODE_VERSION
        value: 20
